[build]
  command = "npm run build"
  publish = "dist"

# Prioritize admin static files
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# React SPA catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
